### ISSUE TITLE
Feat. 질문 발급 통합 테스트 작성

### ISSUE THREAD

**Issue by RokwonK** [kids-ground/adevspoon-backend#102]
### Description
질문 발급 과정 통합 테스트

### Task
- [ ] Controller 통합테스트(MockMvc)
	- [ ] Security, Filter는 어떻게 테스트할까?
	- [ ] 포함해야할까? 빼야할까
- [ ] Persistence Layer 통합테스트
	- [ ] JPA? 쿼리 테스트
	- [ ] Test Container를 통해 MySQL 컨테이너로 띄워서 테스트
- [ ] AOP 통합 테스트(분산락, 유저 활동 이벤트)
	- [ ] 분산락 AOP 로직만 유닛테스트
	- [ ] 분산락 AOP 통합테스트(질문 발급 포함됨) & 동시성 테스트
	- [ ] AOP 로직+비즈니스로직 포함한 통합테스트
