### ISSUE TITLE
[Feature] 요청, 응답 공통 로직 처리

### ISSUE THREAD

**Issue by RokwonK** [kids-ground/adevspoon-backend#4]
### Description
요청, 응답, 예외에 대한 공통 로직 처리

### Task
요청
- [x] 요청 Body, Param 객체 내 특정 key SnakeCase를 CamelCase로 변경하여 받기
- [x] 요청 Body, Param 객체 내 특정 String value를 Enum으로 변경하여 받기

응답
- [x] 성공 시 공통 응답 래핑객체 처리
- [x] 응답 Body 객체 내 특정 key를 SnakeCase로 변경해서 보내기
- [x] 응답 Body 객체 내 특정 Enum value를 String으로 변경하여 보내기

예외
- [x] common 모듈 - 최상위 abstract Custom Exception 정리
- [x] common 모듈 - statusCode별 abstract Exception 정리
- [x] common 모듈 - ErrorCode 정리
- [x] 예외 처리해서 응답보내는 ControllerAdvice 작성
